// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/ajujacob88/go-ecommerce-microservice-clean-arch/go-ecommerce-api-gateway/pkg/api"
	"github.com/ajujacob88/go-ecommerce-microservice-clean-arch/go-ecommerce-api-gateway/pkg/api/handler"
	"github.com/ajujacob88/go-ecommerce-microservice-clean-arch/go-ecommerce-api-gateway/pkg/client"
	"github.com/ajujacob88/go-ecommerce-microservice-clean-arch/go-ecommerce-api-gateway/pkg/config"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.Config) (*api.ServerHTTP, error) {
	configConfig, err := ProvideConfig()
	if err != nil {
		return nil, err
	}
	authClient, err := client.NewAuthClient(configConfig)
	if err != nil {
		return nil, err
	}
	authHandler := handler.NewUserHandler(authClient)
	productClient, err := client.NewProductClient(configConfig)
	if err != nil {
		return nil, err
	}
	productHandler := handler.NewProductHandler(productClient)
	serverHTTP, err := api.NewServerHTTP(configConfig, authHandler, productHandler)
	if err != nil {
		return nil, err
	}
	return serverHTTP, nil
}

// wire.go:

func ProvideConfig() (*config.Config, error) {
	return config.LoadConfig()
}
